import { sitePath } from "@/lib/site-path";

const organisations = [
  { name: "MOL Group", logo: sitePath("/logos/mol.svg") },
  { name: "MVM", logo: sitePath("/logos/mvm.png") },
  { name: "Diageo", logo: sitePath("/logos/diageo.svg") },
  { name: "UNIQA", logo: sitePath("/logos/uniqa.svg") },
  { name: "Hydro", logo: sitePath("/logos/hydro.svg") },
  { name: "MSCI", logo: sitePath("/logos/msci.svg") },
  { name: "Egis", logo: sitePath("/logos/egis.svg") },
  { name: "Vodafone", logo: sitePath("/logos/vodafone.svg") },
  { name: "BMW Group", logo: sitePath("/logos/bmw-group.svg") },
  { name: "Swiss Life", logo: sitePath("/logos/swiss-life.svg") },
] as const;

export const copy = {
  en: {
    brandHome: "Sheralan Consulting home",
    nav: {
      expertise: "Expertise",
      experience: "Experience",
      contact: "Contact",
    },
    menu: "Open navigation",
    language: "Switch to Hungarian",
    hero: {
      eyebrow: "Independent specialist consulting · Budapest / Europe",
      title: "Senior expertise for complex, regulated technology.",
      body: "We solve problems where regulation, governance and implementation meet—with senior specialists in information security, AI and data governance, IT assurance and SAP directly involved from design through delivery.",
      primary: "Discuss a problem",
      secondary: "Explore expertise",
    },
    expertise: {
      kicker: "Selected expertise",
      title: "What we do.",
      intro: "Focused specialist advice at both governance and implementation depth.",
      expand: "View examples",
      collapse: "Back to overview",
      detailKicker: "How we help",
      examplesTitle: "Typical assignments",
      services: [
        {
          id: "security",
          number: "01",
          title: "Information security & regulatory governance",
          summary: "We turn overlapping regulatory and control requirements into operating models, implementable controls and evidence that withstands scrutiny.",
          capabilities: [
            "DORA, NIS2, GDPR, MiCA and Hungarian requirements",
            "Security governance, control architecture and policies",
            "Cloud, third-party risk and operational resilience",
          ],
          detail: "We carry regulatory requirements through to day-to-day operation: clarifying scope and accountability, assessing existing controls, designing the necessary changes and establishing defensible evidence.",
          examples: [
            "DORA or NIS2 assessment and an executable implementation plan",
            "Security governance, policy and control-framework redesign",
            "Cloud, ICT third-party and resilience control implementation",
          ],
        },
        {
          id: "ai",
          number: "02",
          title: "AI, data & privacy governance",
          summary: "We establish practical governance for AI and data use, connecting innovation with privacy, ownership, quality and defensible decision-making.",
          capabilities: [
            "EU AI Act, GDPR, Data Act and governance frameworks",
            "AI and data inventories, classification, ownership and quality",
            "Privacy by design, lifecycle controls and provider assurance",
          ],
          detail: "We put clear ownership and risk-based controls around AI and data use. Work spans use-case intake and classification, approval, privacy and provider assurance through to ongoing monitoring.",
          examples: [
            "EU AI Act inventory, risk classification and compliance roadmap",
            "AI governance model, policy, decision rights and approval workflow",
            "Data ownership and quality model, privacy by design and provider assurance",
          ],
        },
        {
          id: "sap",
          number: "03",
          title: "SAP security, IAM & GRC",
          summary: "We translate control objectives into the SAP roles, rules, workflows, configuration and evidence that make them operational.",
          capabilities: [
            "SAP IAM, authorisation and role design",
            "SAP GRC Access Control, SoD, workflows and provisioning",
            "S/4HANA, Fiori security and SAP penetration testing",
          ],
          detail: "We connect business control objectives to SAP architecture and configuration. Identity lifecycle, roles, GRC workflows, custom development and technical testing are treated as one system, so recommendations remain implementable.",
          examples: [
            "S/4HANA and Fiori role and authorisation redesign",
            "SAP GRC Access Control ruleset, SoD, workflow and HR Trigger",
            "SAP security architecture, penetration testing and remediation verification",
          ],
        },
        {
          id: "audit",
          number: "04",
          title: "IT audit & technology assurance",
          summary: "We assess whether governance, controls and implementations work in practice, producing clear findings and proportionate remediation.",
          capabilities: [
            "IT and cybersecurity audits and internal audit support",
            "Control design and operating-effectiveness testing",
            "Cloud, third-party and implementation assurance",
          ],
          detail: "We test with real evidence whether controls operate, not merely whether they are documented. Design and execution failures are separated, risk-ranked and translated into proportionate remediation.",
          examples: [
            "ITGC and cybersecurity audit or internal audit support",
            "Control-design and operating-effectiveness testing",
            "Cloud, service-provider and system-implementation assurance",
          ],
        },
      ],
    },
    experience: {
      kicker: "Selected experience",
      title: "Enterprise experience behind the team.",
      body: "Selected organisations from individual team members’ professional experience, including roles held before Sheralan Consulting.",
      organisations,
      ariaLabel: "Organisations represented in our professional experience",
    },
    about: {
      kicker: "The team",
      title: "We connect governance with how systems actually work.",
      body: "Sheralan Consulting brings together senior practitioners in information security, data privacy and AI governance, IT audit, technology risk and compliance, SAP architecture, GRC and ABAP engineering, backed by specialist SAP penetration testing. Each lead expert brings more than 15 years of hands-on experience in their respective field. Across the team, that experience spans regulated financial services, energy, pharmaceuticals, telecommunications and manufacturing, as well as multi-country SAP security and GRC programmes and assurance work carried from regulatory interpretation through implementation to technical verification. Clients work directly with the specialists responsible for the analysis and the outcome.",
    },
    contact: {
      kicker: "Contact",
      title: "A difficult technology or governance problem?",
      body: "Send a short description. We will tell you directly whether and how we can help.",
      action: "demeter.nagy@czdconsulting.com",
      availability: "Available in English and Hungarian",
      subject: "Consulting enquiry — Sheralan Consulting",
    },
    footer: {
      legal: "Sheralan Consulting · Czabafy Consulting Kft. · Gárdony, Hungary",
      privacy: "No analytics. No tracking.",
      notice: "Privacy notice",
      company: "Company details",
      legalNavigation: "Legal information",
      top: "Back to top",
    },
  },
  hu: {
    brandHome: "Sheralan Consulting kezdőlap",
    nav: {
      expertise: "Szakterületek",
      experience: "Tapasztalat",
      contact: "Kapcsolat",
    },
    menu: "Navigáció megnyitása",
    language: "Váltás angol nyelvre",
    hero: {
      eyebrow: "Független szakértői tanácsadás · Budapest / Európa",
      title: "Szenior szakértelem összetett, szabályozott technológiai környezetekhez.",
      body: "Azokat a problémákat oldjuk meg, ahol a szabályozási elvárások, az irányítás és a technikai megvalósítás találkozik – információbiztonsági, AI- és adatirányítási, IT-audit- és SAP-szakértőink a tervezéstől a megvalósításig közvetlenül részt vesznek a munkában.",
      primary: "Beszéljünk a feladatról",
      secondary: "Szakterületeink",
    },
    expertise: {
      kicker: "Kiemelt szakterületek",
      title: "Amiben igazán jók vagyunk.",
      intro: "Célzott szakértelem, irányítási és megvalósítási mélységben.",
      expand: "Példák megtekintése",
      collapse: "Vissza az áttekintéshez",
      detailKicker: "Hogyan segítünk",
      examplesTitle: "Tipikus feladatok",
      services: [
        {
          id: "security",
          number: "01",
          title: "Információbiztonság és szabályozási irányítás",
          summary: "Az egymásra épülő szabályozási és kontrollkövetelményeket működő irányítási modellé, bevezethető kontrollokká és auditálható bizonyítékokká alakítjuk.",
          capabilities: [
            "DORA, NIS2, GDPR, MiCA és magyar követelmények",
            "Biztonsági irányítás, kontrollarchitektúra és szabályzatok",
            "Felhő-, harmadikfeles kockázat és működési reziliencia",
          ],
          detail: "A szabályozási elvárásokat végigvezetjük a működésen: tisztázzuk a hatókört és a felelősségeket, felmérjük a meglévő kontrollokat, megtervezzük a szükséges változtatásokat, majd kialakítjuk az auditálható működést és bizonyítékokat.",
          examples: [
            "DORA- vagy NIS2-felmérés és végrehajtható intézkedési terv",
            "Biztonsági irányítás, szabályzat- és kontrollrendszer újratervezése",
            "Felhő-, IKT-harmadikfeles és rezilienciakontrollok bevezetése",
          ],
        },
        {
          id: "ai",
          number: "02",
          title: "AI-, adat- és adatvédelmi irányítás",
          summary: "Az AI- és adatfelhasználás számára olyan működtethető irányítást alakítunk ki, amely összekapcsolja az innovációt az adatvédelemmel, a felelősségi körökkel, az adatminőséggel és a bizonyítható döntéshozatallal.",
          capabilities: [
            "EU AI Act, GDPR, Data Act és irányítási keretrendszerek",
            "AI- és adatnyilvántartás, osztályozás, felelősség és minőség",
            "Beépített adatvédelem, életciklus-kontrollok és szolgáltatói assurance",
          ],
          detail: "Az AI és az adatok használatához egyértelmű felelősségeket és kockázatarányos kontrollokat alakítunk ki. A munka a használati esetek felvételétől és osztályozásától az engedélyezésen, az adatvédelmen és a szolgáltatói ellenőrzésen át a folyamatos nyomon követésig terjed.",
          examples: [
            "EU AI Act szerinti AI-nyilvántartás, kockázati osztályozás és megfelelési terv",
            "AI-irányítási modell, szabályzat, döntési jogkörök és jóváhagyási folyamat",
            "Adatgazdai és adatminőségi modell, beépített adatvédelem és szolgáltatói ellenőrzés",
          ],
        },
        {
          id: "sap",
          number: "03",
          title: "SAP-biztonság, IAM és GRC",
          summary: "A kontrollcélokat az SAP-ban az azokat megvalósító szerepkörökre, szabályokra, workflow-kra, konfigurációra és bizonyítékokra fordítjuk le.",
          capabilities: [
            "SAP IAM-, jogosultság- és szerepkörtervezés",
            "SAP GRC Access Control, SoD, workflow-k és provisioning",
            "S/4HANA-, Fiori-biztonság és SAP penetrációs tesztelés",
          ],
          detail: "Az üzleti kontrollcélokat összekötjük az SAP architektúrájával és konfigurációjával. Az identitás-életciklust, a szerepköröket, a GRC-folyamatokat, az egyedi fejlesztéseket és a műszaki ellenőrzést együtt kezeljük, ezért a javaslataink a célrendszerben ténylegesen megvalósíthatók.",
          examples: [
            "S/4HANA- és Fiori-szerepkörök, valamint jogosultságok újratervezése",
            "SAP GRC Access Control szabályrendszer, SoD, workflow és HR Trigger",
            "SAP-biztonsági architektúra, penetrációs teszt és a javítások visszaellenőrzése",
          ],
        },
        {
          id: "audit",
          number: "04",
          title: "IT-audit és technológiai assurance",
          summary: "Megvizsgáljuk, hogy az irányítás, a kontrollok és a megvalósítás a gyakorlatban is működik-e, majd egyértelmű megállapításokat és arányos javító intézkedéseket adunk.",
          capabilities: [
            "IT- és kiberbiztonsági auditok, belső audit támogatás",
            "Kontrolltervezés és működési hatékonyság tesztelése",
            "Felhő-, harmadikfeles és megvalósítási assurance",
          ],
          detail: "Nemcsak azt vizsgáljuk, hogy egy kontroll dokumentált-e, hanem valódi bizonyítékok alapján azt is, hogy működik-e. A tervezési és végrehajtási hibákat elkülönítjük, kockázat szerint értékeljük, majd megvalósítható javító intézkedésekre fordítjuk.",
          examples: [
            "ITGC- és kiberbiztonsági audit, belső audit szakmai támogatása",
            "Kontrollok kialakításának és működési hatékonyságának tesztelése",
            "Felhő-, szolgáltatói és rendszerbevezetési assurance",
          ],
        },
      ],
    },
    experience: {
      kicker: "Válogatott tapasztalat",
      title: "Nagyvállalati tapasztalat a csapat mögött.",
      body: "Válogatás csapattagjaink egyéni szakmai tapasztalatából, beleértve a Sheralan Consulting létrejötte előtti szerepköröket is.",
      organisations,
      ariaLabel: "Szakmai tapasztalatunkban szereplő szervezetek",
    },
    about: {
      kicker: "A csapat",
      title: "Összekötjük az irányítást a rendszerek tényleges működésével.",
      body: "A Sheralan Consulting szenior szakértői az információbiztonság, az adatvédelem és AI-irányítás, az IT-audit, technológiai kockázat és compliance, valamint az SAP-architektúra, GRC és ABAP-fejlesztés területéről érkeznek; a csapatot specializált SAP penetrációs tesztelési tudás egészíti ki. Vezető szakértőink mindegyike több mint 15 év gyakorlati tapasztalattal rendelkezik saját szakterületén. A csapat együttes tapasztalata szabályozott pénzügyi, energetikai, gyógyszeripari, telekommunikációs és gyártási környezetekre, több országot érintő SAP-biztonsági és GRC-programokra, valamint a szabályozási értelmezéstől a megvalósításon át a műszaki ellenőrzésig végigvitt audit- és technológiai assurance-feladatokra terjed ki. Ügyfeleink közvetlenül azokkal a szakértőkkel dolgoznak, akik az elemzésért és az eredményért felelnek.",
    },
    contact: {
      kicker: "Kapcsolat",
      title: "Összetett technológiai vagy irányítási probléma?",
      body: "Írja le röviden. Egyenesen megmondjuk, hogy tudunk-e és hogyan tudunk segíteni.",
      action: "demeter.nagy@czdconsulting.com",
      availability: "Magyar és angol nyelven",
      subject: "Tanácsadási megkeresés — Sheralan Consulting",
    },
    footer: {
      legal: "Sheralan Consulting · Czabafy Consulting Kft. · Gárdony, Magyarország",
      privacy: "Nincs analitika. Nincs követés.",
      notice: "Adatkezelési tájékoztató",
      company: "Cégadatok",
      legalNavigation: "Jogi információk",
      top: "Vissza az elejére",
    },
  },
} as const;
